#!/bin/sh
echo "php-cs-fixer pre commit hook start"

PHP_CS_FIXER="./vendor/friendsofphp/php-cs-fixer/php-cs-fixer"
PHP_CS_CONFIG="./.php_cs.dist"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [ -n "$CHANGED_FILES" ]; then
    echo "Executing cs fix"
    $PHP_CS_FIXER fix --config "$PHP_CS_CONFIG" $CHANGED_FILES;
    git add $CHANGED_FILES;
fi

echo "php-cs-fixer pre commit hook finish"
